export default {
  parentNotAnArray: 'HV_VAL_ARRAY_CHECK_VALIDATOR_ARRAY_GROUP_PARENT_NOT_AN_ARRAY',
  itemNotAnArray: 'HV_VAL_ARRAY_CHECK_VALIDATOR_ARRAY_GROUP_ITEM_NOT_AN_ARRAY',
  itemLengthError: 'HV_VAL_ARRAY_CHECK_VALIDATOR_ARRAY_GROUP_ITEM_LENGTH_ERROR',
  itemTypesError: 'HV_VAL_ARRAY_CHECK_VALIDATOR_ARRAY_GROUP_ITEM_TYPES_ERROR',
  unknownOperator: 'HV_VAL_ARRAY_UNKNOWN_OPERATOR',
};
