export default {
  ARGUMENTS: {
    VALIDATOR: {
      IS_NOT_A_STRING: 'ARGUMENTS_VALIDATOR_IS_NOT_A_STRING | [...]',
      IS_EMPTY: 'ARGUMENTS_VALIDATOR_IS_EMPTY | [...]',
      ERROR: 'ARGUMENTS_VALIDATOR_ERROR | [...]',
    },
  },
  VALIDATOR: {
    UNKNOWN: 'VALIDATOR_UNKNOWN | %s | [...]',
  },
  STRING: {
    NO_APOSTROPHES: 'STRING_NO_APOSTROPHES | [...]',
  },
  ISEQUALTO: {
    NO_VALUES_PASSED: 'ISEQUALTO_NO_VALUES_PASSED | [...]',
  },
};
