export default {
  ARGUMENTS: {
    VALIDATOR: {
      IS_UNDEFINED: 'ARGUMENTS_VALIDATOR_IS_UNDEFINED | [...]',
      IS_NOT_A_STRING: 'ARGUMENTS_VALIDATOR_IS_NOT_A_STRING | [...]',
      IS_EMPTY: 'ARGUMENTS_VALIDATOR_IS_EMPTY | [...]',
      ERROR: 'ARGUMENTS_VALIDATOR_ERROR | [...]',
    },
  },
  VALIDATOR: {
    UNKNOWN: 'VALIDATOR_UNKNOWN | %s | [...]',
    RETHINK: 'VALIDATOR_RETHINK | [...]'
  }
};
